name = "myhomegames-tunnel-manager"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[[routes]]
pattern = "myhomegames-server.vige.it/*"
zone_name = "vige.it"

[[routes]]
pattern = "*-myhomegames-server.vige.it/igdb/*"
zone_name = "vige.it"

[vars]
MYGAMES_ACCOUNT_ID = "d2633016ba82b226e5596563e44ced6d"
